<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ryan Ellis (PID: A17673864)">

<title>Class 08: Breast Cancer Mini Proj</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="class08_files/libs/clipboard/clipboard.min.js"></script>
<script src="class08_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="class08_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="class08_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="class08_files/libs/quarto-html/popper.min.js"></script>
<script src="class08_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="class08_files/libs/quarto-html/anchor.min.js"></script>
<link href="class08_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="class08_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="class08_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="class08_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="class08_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import">Data Import</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
  <li><a href="#principle-component-analysis-pca" id="toc-principle-component-analysis-pca" class="nav-link" data-scroll-target="#principle-component-analysis-pca">Principle Component Analysis (PCA)</a></li>
  <li><a href="#lets-visualize" id="toc-lets-visualize" class="nav-link" data-scroll-target="#lets-visualize">Lets visualize</a></li>
  <li><a href="#varaince" id="toc-varaince" class="nav-link" data-scroll-target="#varaince">Varaince</a></li>
  <li><a href="#commuicating-pca-results" id="toc-commuicating-pca-results" class="nav-link" data-scroll-target="#commuicating-pca-results">Commuicating PCA Results</a></li>
  <li><a href="#hierarchical-clustering" id="toc-hierarchical-clustering" class="nav-link" data-scroll-target="#hierarchical-clustering">Hierarchical Clustering</a></li>
  <li><a href="#combine-methods" id="toc-combine-methods" class="nav-link" data-scroll-target="#combine-methods">Combine Methods</a></li>
  <li><a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction">Prediction</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Class 08: Breast Cancer Mini Proj</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ryan Ellis (PID: A17673864) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>The goal of this mini-project is for you to explore a complete analysis using the unsupervised learning techniques covered in class.</p>
<p>We will analyze a data set describing a fine needle aspiration (FNA) of a breast mass.</p>
</section>
<section id="data-import" class="level2">
<h2 class="anchored" data-anchor-id="data-import">Data Import</h2>
<p>The data is made available as a CSV file for download. We can use the <code>read.csv()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># IMPORTANT TO SET ROW NAMES EQUAL TO ONE</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>wisc.df<span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"WisconsinCancer.csv"</span>, <span class="at">row.names=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wisc.df, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         diagnosis radius_mean texture_mean perimeter_mean area_mean
842302           M       17.99        10.38          122.8      1001
842517           M       20.57        17.77          132.9      1326
84300903         M       19.69        21.25          130.0      1203
         smoothness_mean compactness_mean concavity_mean concave.points_mean
842302           0.11840          0.27760         0.3001             0.14710
842517           0.08474          0.07864         0.0869             0.07017
84300903         0.10960          0.15990         0.1974             0.12790
         symmetry_mean fractal_dimension_mean radius_se texture_se perimeter_se
842302          0.2419                0.07871    1.0950     0.9053        8.589
842517          0.1812                0.05667    0.5435     0.7339        3.398
84300903        0.2069                0.05999    0.7456     0.7869        4.585
         area_se smoothness_se compactness_se concavity_se concave.points_se
842302    153.40      0.006399        0.04904      0.05373           0.01587
842517     74.08      0.005225        0.01308      0.01860           0.01340
84300903   94.03      0.006150        0.04006      0.03832           0.02058
         symmetry_se fractal_dimension_se radius_worst texture_worst
842302       0.03003             0.006193        25.38         17.33
842517       0.01389             0.003532        24.99         23.41
84300903     0.02250             0.004571        23.57         25.53
         perimeter_worst area_worst smoothness_worst compactness_worst
842302             184.6       2019           0.1622            0.6656
842517             158.8       1956           0.1238            0.1866
84300903           152.5       1709           0.1444            0.4245
         concavity_worst concave.points_worst symmetry_worst
842302            0.7119               0.2654         0.4601
842517            0.2416               0.1860         0.2750
84300903          0.4504               0.2430         0.3613
         fractal_dimension_worst
842302                   0.11890
842517                   0.08902
84300903                 0.08758</code></pre>
</div>
</div>
<p>We need to exclude the <code>diagnosis</code> column for analysis as this is the answer we are trying to achieve.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This will give us everything but the first column</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>wisc.data <span class="ot">&lt;-</span> wisc.df[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>diagnosis<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(wisc.df<span class="sc">$</span>diagnosis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<blockquote class="blockquote">
<p>Q1. How many observations are in this dataset?</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(wisc.df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 569</code></pre>
</div>
</div>
<p>There are 569 patients or observations.</p>
<blockquote class="blockquote">
<p>Q2. How many of the observations have a malignant diagnosis?</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(diagnosis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>diagnosis
  B   M 
357 212 </code></pre>
</div>
</div>
<p>There are 357 benign and 212 are malignant.</p>
<blockquote class="blockquote">
<p>Q3. How many variables/features in the data are suffixed with _mean?</p>
</blockquote>
<p>We can use the <code>grep()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(wisc.data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "radius_mean"             "texture_mean"           
 [3] "perimeter_mean"          "area_mean"              
 [5] "smoothness_mean"         "compactness_mean"       
 [7] "concavity_mean"          "concave.points_mean"    
 [9] "symmetry_mean"           "fractal_dimension_mean" 
[11] "radius_se"               "texture_se"             
[13] "perimeter_se"            "area_se"                
[15] "smoothness_se"           "compactness_se"         
[17] "concavity_se"            "concave.points_se"      
[19] "symmetry_se"             "fractal_dimension_se"   
[21] "radius_worst"            "texture_worst"          
[23] "perimeter_worst"         "area_worst"             
[25] "smoothness_worst"        "compactness_worst"      
[27] "concavity_worst"         "concave.points_worst"   
[29] "symmetry_worst"          "fractal_dimension_worst"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">grep</span>(<span class="st">"_mean"</span>,<span class="fu">colnames</span>(wisc.data)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
</div>
<p>There are 10 variables with <code>_mean</code></p>
</section>
<section id="principle-component-analysis-pca" class="level2">
<h2 class="anchored" data-anchor-id="principle-component-analysis-pca">Principle Component Analysis (PCA)</h2>
<p>Need to scale data before PCA. <code>scale=TRUE</code> in the argument of <code>prcomp()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## In general will always want to include scaling, will make the plots easier to interpret and present </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>wisc.pr<span class="ot">&lt;-</span> <span class="fu">prcomp</span>(wisc.data, <span class="at">scale=</span><span class="cn">TRUE</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wisc.pr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2     PC3     PC4     PC5     PC6     PC7
Standard deviation     3.6444 2.3857 1.67867 1.40735 1.28403 1.09880 0.82172
Proportion of Variance 0.4427 0.1897 0.09393 0.06602 0.05496 0.04025 0.02251
Cumulative Proportion  0.4427 0.6324 0.72636 0.79239 0.84734 0.88759 0.91010
                           PC8    PC9    PC10   PC11    PC12    PC13    PC14
Standard deviation     0.69037 0.6457 0.59219 0.5421 0.51104 0.49128 0.39624
Proportion of Variance 0.01589 0.0139 0.01169 0.0098 0.00871 0.00805 0.00523
Cumulative Proportion  0.92598 0.9399 0.95157 0.9614 0.97007 0.97812 0.98335
                          PC15    PC16    PC17    PC18    PC19    PC20   PC21
Standard deviation     0.30681 0.28260 0.24372 0.22939 0.22244 0.17652 0.1731
Proportion of Variance 0.00314 0.00266 0.00198 0.00175 0.00165 0.00104 0.0010
Cumulative Proportion  0.98649 0.98915 0.99113 0.99288 0.99453 0.99557 0.9966
                          PC22    PC23   PC24    PC25    PC26    PC27    PC28
Standard deviation     0.16565 0.15602 0.1344 0.12442 0.09043 0.08307 0.03987
Proportion of Variance 0.00091 0.00081 0.0006 0.00052 0.00027 0.00023 0.00005
Cumulative Proportion  0.99749 0.99830 0.9989 0.99942 0.99969 0.99992 0.99997
                          PC29    PC30
Standard deviation     0.02736 0.01153
Proportion of Variance 0.00002 0.00000
Cumulative Proportion  1.00000 1.00000</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q4. From your results, what proportion of the original variance is captured by the first principal component (PC1)?</p>
</blockquote>
<p>Around 44.27% of the data is captured via PC1</p>
<blockquote class="blockquote">
<p>Q5. How many principal components (PCs) are required to describe at least 70% of the original variance in the data?</p>
</blockquote>
<p>To describe 70% of the data you need at least the first three PC’s so PC1-PC3</p>
<blockquote class="blockquote">
<p>Q6. How many principal components (PCs) are required to describe at least 90% of the original variance in the data?</p>
</blockquote>
<p>To get to 90% cumulative proportion it is necessary to have 7 principal components (PC1-PC7)</p>
</section>
<section id="lets-visualize" class="level2">
<h2 class="anchored" data-anchor-id="lets-visualize">Lets visualize</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(wisc.pr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="class08_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Q7. What stands out to you about this plot? Is it easy or difficult to understand? Why?</p>
</blockquote>
<p>The sheer amount of data that this plot is trying to visualize. It is extremely difficult to visualize much of anything within the plot due to the number of points and different thing occurring.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wisc.pr<span class="sc">$</span>x)<span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(PC1, PC2, <span class="at">col=</span>diagnosis)<span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="class08_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Q8. Generate a similar plot for principal components 1 and 3. What do you notice about these plots?</p>
</blockquote>
<p>That both PC1/PC2 and PC1/PC3 are separated via diagnosis on PC1 axis, but both heavily overlap in PC2 and PC3. PC1 captures the most amount of variance.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wisc.pr<span class="sc">$</span>x)<span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(PC1, PC3, <span class="at">col=</span>diagnosis)<span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="class08_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="varaince" class="level2">
<h2 class="anchored" data-anchor-id="varaince">Varaince</h2>
<p>We will make a scree plot, which will show us the variance that each PC indicates. Basically creates a exponential graph (hill), that will show when adding new PC’s doesn’t really make sense anymore.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>pr.var<span class="ot">&lt;-</span>(wisc.pr<span class="sc">$</span>sdev<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pve<span class="ot">&lt;-</span> ((pr.var)<span class="sc">/</span>(<span class="dv">30</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">c</span>(<span class="dv">1</span>,pve), <span class="at">xlab =</span> <span class="st">"Principal Component"</span>, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Proportion of Variance Explained"</span>, </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">type =</span> <span class="st">"o"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="class08_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="commuicating-pca-results" class="level2">
<h2 class="anchored" data-anchor-id="commuicating-pca-results">Commuicating PCA Results</h2>
<blockquote class="blockquote">
<p>Q9. For the first principal component, what is the component of the loading vector (i.e.&nbsp;wisc.pr$rotation[,1]) for the feature concave.points_mean? This tells us how much this original feature contributes to the first PC. Are there any features with larger contributions than this one?</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>wisc.pr<span class="sc">$</span>rotation[,<span class="sc">-</span><span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                 PC2          PC3          PC4          PC5
radius_mean              0.233857132 -0.008531243  0.041408962 -0.037786354
texture_mean             0.059706088  0.064549903 -0.603050001  0.049468850
perimeter_mean           0.215181361 -0.009314220  0.041983099 -0.037374663
area_mean                0.231076711  0.028699526  0.053433795 -0.010331251
smoothness_mean         -0.186113023 -0.104291904  0.159382765  0.365088528
compactness_mean        -0.151891610 -0.074091571  0.031794581 -0.011703971
concavity_mean          -0.060165363  0.002733838  0.019122753 -0.086375412
concave.points_mean      0.034767500 -0.025563541  0.065335944  0.043861025
symmetry_mean           -0.190348770 -0.040239936  0.067124984  0.305941428
fractal_dimension_mean  -0.366575471 -0.022574090  0.048586765  0.044424360
radius_se                0.105552152  0.268481387  0.097941242  0.154456496
texture_se              -0.089979682  0.374633665 -0.359855528  0.191650506
perimeter_se             0.089457234  0.266645367  0.088992415  0.120990220
area_se                  0.152292628  0.216006528  0.108205039  0.127574432
smoothness_se           -0.204430453  0.308838979  0.044664180  0.232065676
compactness_se          -0.232715896  0.154779718 -0.027469363 -0.279968156
concavity_se            -0.197207283  0.176463743  0.001316880 -0.353982091
concave.points_se       -0.130321560  0.224657567  0.074067335 -0.195548089
symmetry_se             -0.183848000  0.288584292  0.044073351  0.252868765
fractal_dimension_se    -0.280092027  0.211503764  0.015304750 -0.263297438
radius_worst             0.219866379 -0.047506990  0.015417240  0.004406592
texture_worst            0.045467298 -0.042297823 -0.632807885  0.092883400
perimeter_worst          0.199878428 -0.048546508  0.013802794 -0.007454151
area_worst               0.219351858 -0.011902318  0.025894749  0.027390903
smoothness_worst        -0.172304352 -0.259797613  0.017652216  0.324435445
compactness_worst       -0.143593173 -0.236075625 -0.091328415 -0.121804107
concavity_worst         -0.097964114 -0.173057335 -0.073951180 -0.188518727
concave.points_worst     0.008257235 -0.170344076  0.006006996 -0.043332069
symmetry_worst          -0.141883349 -0.271312642 -0.036250695  0.244558663
fractal_dimension_worst -0.275339469 -0.232791313 -0.077053470 -0.094423351
                                  PC6           PC7          PC8          PC9
radius_mean              0.0187407904 -0.1240883403  0.007452296 -0.223109764
texture_mean            -0.0321788366  0.0113995382 -0.130674825  0.112699390
perimeter_mean           0.0173084449 -0.1144770573  0.018687258 -0.223739213
area_mean               -0.0018877480 -0.0516534275 -0.034673604 -0.195586014
smoothness_mean         -0.2863744966 -0.1406689928  0.288974575  0.006424722
compactness_mean        -0.0141309489  0.0309184960  0.151396350 -0.167841425
concavity_mean          -0.0093441809 -0.1075204434  0.072827285  0.040591006
concave.points_mean     -0.0520499505 -0.1504822142  0.152322414 -0.111971106
symmetry_mean            0.3564584607 -0.0938911345  0.231530989  0.256040084
fractal_dimension_mean  -0.1194306679  0.2957600240  0.177121441 -0.123740789
radius_se               -0.0256032561  0.3124900373 -0.022539967  0.249985002
texture_se              -0.0287473145 -0.0907553556  0.475413139 -0.246645397
perimeter_se             0.0018107150  0.3146403902  0.011896690  0.227154024
area_se                 -0.0428639079  0.3466790028 -0.085805135  0.229160015
smoothness_se           -0.3429173935 -0.2440240556 -0.573410232 -0.141924890
compactness_se           0.0691975186  0.0234635340 -0.117460157 -0.145322810
concavity_se             0.0563432386 -0.2088237897 -0.060566501  0.358107079
concave.points_se       -0.0312244482 -0.3696459369  0.108319309  0.272519886
symmetry_se              0.4902456426 -0.0803822539 -0.220149279 -0.304077200
fractal_dimension_se    -0.0531952674  0.1913949726 -0.011168188 -0.213722716
radius_worst            -0.0002906849 -0.0097099360 -0.042619416 -0.112141463
texture_worst           -0.0500080613  0.0098707439 -0.036251636  0.103341204
perimeter_worst          0.0085009872 -0.0004457267 -0.030558534 -0.109614364
area_worst              -0.0251643821  0.0678316595 -0.079394246 -0.080732461
smoothness_worst        -0.3692553703 -0.1088308865 -0.205852191  0.112315904
compactness_worst        0.0477057929  0.1404729381 -0.084019659 -0.100677822
concavity_worst          0.0283792555 -0.0604880561 -0.072467871  0.161908621
concave.points_worst    -0.0308734498 -0.1679666187  0.036170795  0.060488462
symmetry_worst           0.4989267845 -0.0184906298 -0.228225053  0.064637806
fractal_dimension_worst -0.0802235245  0.3746576261 -0.048360667 -0.134174175
                                PC10        PC11         PC12        PC13
radius_mean              0.095486443 -0.04147149  0.051067457  0.01196721
texture_mean             0.240934066  0.30224340  0.254896423  0.20346133
perimeter_mean           0.086385615 -0.01678264  0.038926106  0.04410950
area_mean                0.074956489 -0.11016964  0.065437508  0.06737574
smoothness_mean         -0.069292681  0.13702184  0.316727211  0.04557360
compactness_mean         0.012936200  0.30800963 -0.104017044  0.22928130
concavity_mean          -0.135602298 -0.12419024  0.065653480  0.38709081
concave.points_mean      0.008054528  0.07244603  0.042589267  0.13213810
symmetry_mean            0.572069479 -0.16305408 -0.288865504  0.18993367
fractal_dimension_mean   0.081103207  0.03804827  0.236358988  0.10623908
radius_se               -0.049547594  0.02535702 -0.016687915 -0.06819523
texture_se              -0.289142742 -0.34494446 -0.306160423 -0.16822238
perimeter_se            -0.114508236  0.16731877 -0.101446828 -0.03784399
area_se                 -0.091927889 -0.05161946 -0.017679218  0.05606493
smoothness_se            0.160884609 -0.08420621 -0.294710053  0.15044143
compactness_se           0.043504866  0.20688568 -0.263456509  0.01004017
concavity_se            -0.141276243 -0.34951794  0.251146975  0.15878319
concave.points_se        0.086240847  0.34237591 -0.006458751 -0.49402674
symmetry_se             -0.316529830  0.18784404  0.320571348  0.01033274
fractal_dimension_se     0.367541918 -0.25062479  0.276165974 -0.24045832
radius_worst             0.077361643 -0.10506733  0.039679665 -0.13789053
texture_worst            0.029550941 -0.01315727  0.079797450 -0.08014543
perimeter_worst          0.050508334 -0.05107628 -0.008987738 -0.09696571
area_worst               0.069921152 -0.18459894  0.048088657 -0.10116061
smoothness_worst        -0.128304659 -0.14389035  0.056514866 -0.20513034
compactness_worst       -0.172133632  0.19742047 -0.371662503  0.01227931
concavity_worst         -0.311638520 -0.18501676 -0.087034532  0.21798433
concave.points_worst    -0.076648291  0.11777205 -0.068125354 -0.25438749
symmetry_worst          -0.029563075 -0.15756025  0.044033503 -0.25653491
fractal_dimension_worst  0.012609579 -0.11828355 -0.034731693 -0.17281424
                                PC14         PC15        PC16         PC17
radius_mean              0.059506135 -0.051118775 -0.15058388  0.202924255
texture_mean            -0.021560100 -0.107922421 -0.15784196 -0.038706119
perimeter_mean           0.048513812 -0.039902936 -0.11445396  0.194821310
area_mean                0.010830829  0.013966907 -0.13244803  0.255705763
smoothness_mean          0.445064860 -0.118143364 -0.20461325  0.167929914
compactness_mean         0.008101057  0.230899962  0.17017837 -0.020307708
concavity_mean          -0.189358699 -0.128283732  0.26947021 -0.001598353
concave.points_mean     -0.244794768 -0.217099194  0.38046410  0.034509509
symmetry_mean            0.030738856 -0.073961707 -0.16466159 -0.191737848
fractal_dimension_mean  -0.377078865  0.517975705 -0.04079279  0.050225246
radius_se                0.010347413 -0.110050711  0.05890572 -0.139396866
texture_se              -0.010849347  0.032752721 -0.03450040  0.043963016
perimeter_se            -0.045523718 -0.008268089  0.02651665 -0.024635639
area_se                  0.083570718 -0.046024366  0.04115323  0.334418173
smoothness_se           -0.201152530  0.018559465 -0.05803906  0.139595006
compactness_se           0.491755932  0.168209315  0.18983090 -0.008246477
concavity_se             0.134586924  0.250471408 -0.12542065  0.084616716
concave.points_se       -0.199666719  0.062079344 -0.19881035  0.108132263
symmetry_se             -0.046864383 -0.113383199 -0.15771150 -0.274059129
fractal_dimension_se     0.145652466 -0.353232211  0.26855388 -0.122733398
radius_worst             0.023101281  0.166567074 -0.08156057 -0.240049982
texture_worst            0.053430792  0.101115399  0.18555785  0.069365185
perimeter_worst          0.012219382  0.182755198 -0.05485705 -0.234164147
area_worst              -0.006685465  0.314993600 -0.09065339 -0.273399584
smoothness_worst         0.162235443  0.046125866  0.14555166 -0.278030197
compactness_worst        0.166470250 -0.049956014 -0.15373486 -0.004037123
concavity_worst         -0.066798931 -0.204835886 -0.21502195 -0.191313419
concave.points_worst    -0.276418891 -0.169499607  0.17814174 -0.075485316
symmetry_worst           0.005355574  0.139888394  0.25789401  0.430658116
fractal_dimension_worst -0.212104110 -0.256173195 -0.40555649  0.159394300
                                 PC18        PC19         PC20          PC21
radius_mean              0.1467123385  0.22538466 -0.049698664 -0.0685700057
texture_mean            -0.0411029851  0.02978864 -0.244134993  0.4483694667
perimeter_mean           0.1583174548  0.23959528 -0.017665012 -0.0697690429
area_mean                0.2661681046 -0.02732219 -0.090143762 -0.0184432785
smoothness_mean         -0.3522268017 -0.16456584  0.017100960 -0.1194917473
compactness_mean         0.0077941384  0.28422236  0.488686329  0.1926213963
concavity_mean          -0.0269681105  0.00226636 -0.033387086  0.0055717533
concave.points_mean     -0.0828277367 -0.15497236 -0.235407606 -0.0094238187
symmetry_mean            0.1733977905 -0.05881116  0.026069156 -0.0869384844
fractal_dimension_mean   0.0878673570 -0.05815705 -0.175637222 -0.0762718362
radius_se               -0.2362165319  0.17588331 -0.090800503  0.0863867747
texture_se              -0.0098586620  0.03600985 -0.071659988  0.2170719674
perimeter_se            -0.0259288003  0.36570154 -0.177250625 -0.3049501584
area_se                  0.3049069032 -0.41657231  0.274201148  0.1925877857
smoothness_se           -0.2312599432 -0.01326009  0.090061477 -0.0720987261
compactness_se           0.1004742346 -0.24244818 -0.461098220 -0.1403865724
concavity_se            -0.0001954852  0.12638102  0.066946174  0.0630479298
concave.points_se        0.0460549116 -0.01216430  0.068868294  0.0343753236
symmetry_se              0.1870147640 -0.08903929  0.107385289 -0.0976995265
fractal_dimension_se    -0.0598230982  0.08660084  0.222345297  0.0628432814
radius_worst            -0.2161013526  0.01366130 -0.005626909  0.0072938995
texture_worst            0.0583984505 -0.07586693  0.300599798 -0.5944401434
perimeter_worst         -0.1885435919  0.09081325  0.011003858 -0.0920235990
area_worst              -0.1420648558 -0.41004720  0.060047387  0.1467901315
smoothness_worst         0.5015516751  0.23451384 -0.129723903  0.1648492374
compactness_worst       -0.0735745143  0.02020070  0.229280589  0.1813748671
concavity_worst         -0.1039079796 -0.04578612 -0.046482792 -0.1321005945
concave.points_worst     0.0758138963 -0.26022962  0.033022340  0.0008860815
symmetry_worst          -0.2787138431  0.11725053 -0.116759236  0.1627085487
fractal_dimension_worst  0.0235647497 -0.01149448 -0.104991974 -0.0923439434
                               PC22          PC23        PC24        PC25
radius_mean             -0.07292890 -0.0985526942 -0.18257944 -0.01922650
texture_mean            -0.09480063 -0.0005549975  0.09878679  0.08474593
perimeter_mean          -0.07516048 -0.0402447050 -0.11664888  0.02701541
area_mean               -0.09756578  0.0077772734  0.06984834 -0.21004078
smoothness_mean         -0.06382295 -0.0206657211  0.06869742  0.02895489
compactness_mean         0.09807756  0.0523603957 -0.10413552  0.39662323
concavity_mean           0.18521200  0.3248703785  0.04474106 -0.09697732
concave.points_mean      0.31185243 -0.0514087968  0.08402770 -0.18645160
symmetry_mean            0.01840673 -0.0512005770  0.01933947 -0.02458369
fractal_dimension_mean  -0.28786888 -0.0846898562 -0.13326055 -0.20722186
radius_se                0.15027468 -0.2641253170 -0.55870157 -0.17493043
texture_se              -0.04845693 -0.0008738805  0.02426730  0.05698648
perimeter_se            -0.15935280  0.0900742110  0.51675039  0.07292764
area_se                 -0.06423262  0.0982150746 -0.02246072  0.13185041
smoothness_se           -0.05054490 -0.0598177179  0.01563119  0.03121070
compactness_se           0.04528769  0.0091038710 -0.12177779  0.17316455
concavity_se             0.20521269 -0.3875423290  0.18820504  0.01593998
concave.points_se        0.07254538  0.3517550738 -0.10966898 -0.12954655
symmetry_se              0.08465443 -0.0423628949  0.00322620 -0.01951493
fractal_dimension_se    -0.24470508  0.0857810992  0.07519442 -0.08417120
radius_worst             0.09629821 -0.0556767923 -0.15683037  0.07070972
texture_worst            0.11111202 -0.0089228997 -0.11848460 -0.11818972
perimeter_worst         -0.01722163  0.0633448296  0.23711317  0.11803403
area_worst               0.09695982  0.1908896250  0.14406303 -0.03828995
smoothness_worst         0.06825409  0.0936901494 -0.01099014 -0.04796476
compactness_worst       -0.02967641 -0.1479209247  0.18674995 -0.62438494
concavity_worst         -0.46042619  0.2864331353 -0.28885257  0.11577034
concave.points_worst    -0.29984056 -0.5675277966  0.10734024  0.26319634
symmetry_worst          -0.09714484  0.1213434508 -0.01438181  0.04529962
fractal_dimension_worst  0.46947115  0.0076253382  0.03782545  0.28013348
                                PC26         PC27          PC28          PC29
radius_mean             -0.129476396 -0.131526670  2.111940e-01  2.114605e-01
texture_mean            -0.024556664 -0.017357309 -6.581146e-05 -1.053393e-02
perimeter_mean          -0.125255946 -0.115415423  8.433827e-02  3.838261e-01
area_mean                0.362727403  0.466612477 -2.725083e-01 -4.227949e-01
smoothness_mean         -0.037003686  0.069689923  1.479269e-03 -3.434667e-03
compactness_mean         0.262808474  0.097748705 -5.462767e-03 -4.101677e-02
concavity_mean          -0.548876170  0.364808397  4.553864e-02 -1.001479e-02
concave.points_mean      0.387643377 -0.454699351 -8.883097e-03 -4.206949e-03
symmetry_mean           -0.016044038 -0.015164835  1.433026e-03 -7.569862e-03
fractal_dimension_mean  -0.097404839 -0.101244946 -6.311687e-03  7.301433e-03
radius_se                0.049977080  0.212982901 -1.922239e-01  1.184421e-01
texture_se              -0.011237242 -0.010092889 -5.622611e-03 -8.776279e-03
perimeter_se             0.103653282  0.041691553  2.631919e-01 -6.100219e-03
area_se                 -0.155304589 -0.313358657 -4.206811e-02 -8.592591e-02
smoothness_se           -0.007717557 -0.009052154  9.792963e-03  1.776386e-03
compactness_se          -0.049727632  0.046536088 -1.539555e-02  3.158134e-03
concavity_se             0.091454968 -0.084224797  5.820978e-03  1.607852e-02
concave.points_se       -0.017941919 -0.011165509 -2.900930e-02 -2.393779e-02
symmetry_se             -0.017267849 -0.019975983 -7.636526e-03 -5.223292e-03
fractal_dimension_se     0.035488974 -0.012036564  1.975646e-02 -8.341912e-03
radius_worst            -0.197054744 -0.178666740  4.126396e-01 -6.357249e-01
texture_worst            0.036469433  0.021410694 -3.902509e-04  1.723549e-02
perimeter_worst         -0.244103670 -0.241031046 -7.286809e-01  2.292180e-02
area_worst               0.231359525  0.237162466  2.389603e-01  4.449359e-01
smoothness_worst         0.012602464 -0.040853568 -1.535248e-03  7.385492e-03
compactness_worst       -0.100463424 -0.070505414  4.869182e-02  3.566904e-06
concavity_worst          0.266853781 -0.142905801 -1.764090e-02 -1.267572e-02
concave.points_worst    -0.133574507  0.230901389  2.247567e-02  3.524045e-02
symmetry_worst           0.028184296  0.022790444  4.920481e-03  1.340423e-02
fractal_dimension_worst  0.004520482  0.059985998 -2.356214e-02  1.147766e-02
                                 PC30
radius_mean              0.7024140910
texture_mean             0.0002736610
perimeter_mean          -0.6898969685
area_mean               -0.0329473482
smoothness_mean         -0.0048474577
compactness_mean         0.0446741863
concavity_mean           0.0251386661
concave.points_mean     -0.0010772653
symmetry_mean           -0.0012803794
fractal_dimension_mean  -0.0047556848
radius_se               -0.0087110937
texture_se              -0.0010710392
perimeter_se             0.0137293906
area_se                  0.0011053260
smoothness_se           -0.0016082109
compactness_se           0.0019156224
concavity_se            -0.0089265265
concave.points_se       -0.0021601973
symmetry_se              0.0003293898
fractal_dimension_se     0.0017989568
radius_worst            -0.1356430561
texture_worst            0.0010205360
perimeter_worst          0.0797438536
area_worst               0.0397422838
smoothness_worst         0.0045832773
compactness_worst       -0.0128415624
concavity_worst          0.0004021392
concave.points_worst    -0.0022884418
symmetry_worst           0.0003954435
fractal_dimension_worst  0.0018942925</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grep</span>(<span class="st">"concave.points_mean"</span>,wisc.pr<span class="sc">$</span>rotation[,<span class="sc">-</span><span class="dv">1</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
</section>
<section id="hierarchical-clustering" class="level2">
<h2 class="anchored" data-anchor-id="hierarchical-clustering">Hierarchical Clustering</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>wisc.hclust <span class="ot">&lt;-</span> <span class="fu">hclust</span>(<span class="fu">dist</span>(<span class="fu">scale</span>(wisc.data)))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wisc.hclust)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="class08_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="combine-methods" class="level2">
<h2 class="anchored" data-anchor-id="combine-methods">Combine Methods</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>d<span class="ot">&lt;-</span><span class="fu">dist</span>(wisc.pr<span class="sc">$</span>x[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>wisc.pr.hclust<span class="ot">&lt;-</span> <span class="fu">hclust</span>(d, <span class="at">method=</span><span class="st">"ward.D2"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wisc.pr.hclust)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">75</span>, <span class="at">col=</span><span class="st">"green"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="class08_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>grps<span class="ot">&lt;-</span> <span class="fu">cutree</span>(wisc.pr.hclust, <span class="at">h=</span><span class="dv">75</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(grps)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>grps
  1   2 
171 398 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># These results are similar to the diagnosis, where we cluster the two groups into Malignant and Beningn</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>How does this clustering in <code>grps()</code> correspond to the expert <code>diagnosis</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(diagnosis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>diagnosis
  B   M 
357 212 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(diagnosis, grps)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         grps
diagnosis   1   2
        B   6 351
        M 165  47</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q13. How well does the newly created hclust model with two clusters separate out the two “M” and “B” diagnoses?</p>
</blockquote>
<p>It does decently when we compare it to the expert diagnosis, it shows that we have 6 false positive for benign and 47 false negatives for malignant. This is shown in the table above plotted grps versus diagnosis.</p>
<blockquote class="blockquote">
<p>Q14. How well do the hierarchical clustering models you created in the previous sections (i.e.&nbsp;without first doing PCA) do in terms of separating the diagnoses? Again, use the table() function to compare the output of each model (wisc.hclust.clusters and wisc.pr.hclust.clusters) with the vector containing the actual diagnoses.</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>wisc.hclust.clusters <span class="ot">&lt;-</span> <span class="fu">cutree</span>(wisc.hclust, <span class="at">k=</span><span class="dv">2</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(diagnosis,wisc.hclust.clusters)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         wisc.hclust.clusters
diagnosis   1   2
        B 357   0
        M 210   2</code></pre>
</div>
</div>
<p>Before using PCA, we can see that there is almost no separation between the two types, benign and malignant. Although when using PCA we have some false negative and positives, without it we cant really even interpret anything.</p>
</section>
<section id="prediction" class="level2">
<h2 class="anchored" data-anchor-id="prediction">Prediction</h2>
<p>We will now utilize the <code>predict()</code> function to combine our previous PCA model and and some new data (cancer cell data)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://tinyurl.com/new-samples-CSV"</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(url)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>npc <span class="ot">&lt;-</span> <span class="fu">predict</span>(wisc.pr, <span class="at">newdata=</span>new)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>npc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           PC1       PC2        PC3        PC4       PC5        PC6        PC7
[1,]  2.576616 -3.135913  1.3990492 -0.7631950  2.781648 -0.8150185 -0.3959098
[2,] -4.754928 -3.009033 -0.1660946 -0.6052952 -1.140698 -1.2189945  0.8193031
            PC8       PC9       PC10      PC11      PC12      PC13     PC14
[1,] -0.2307350 0.1029569 -0.9272861 0.3411457  0.375921 0.1610764 1.187882
[2,] -0.3307423 0.5281896 -0.4855301 0.7173233 -1.185917 0.5893856 0.303029
          PC15       PC16        PC17        PC18        PC19       PC20
[1,] 0.3216974 -0.1743616 -0.07875393 -0.11207028 -0.08802955 -0.2495216
[2,] 0.1299153  0.1448061 -0.40509706  0.06565549  0.25591230 -0.4289500
           PC21       PC22       PC23       PC24        PC25         PC26
[1,]  0.1228233 0.09358453 0.08347651  0.1223396  0.02124121  0.078884581
[2,] -0.1224776 0.01732146 0.06316631 -0.2338618 -0.20755948 -0.009833238
             PC27        PC28         PC29         PC30
[1,]  0.220199544 -0.02946023 -0.015620933  0.005269029
[2,] -0.001134152  0.09638361  0.002795349 -0.019015820</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wisc.pr<span class="sc">$</span>x[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">col=</span>grps)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(npc[,<span class="dv">1</span>], npc[,<span class="dv">2</span>], <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">pch=</span><span class="dv">16</span>, <span class="at">cex=</span><span class="dv">3</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(npc[,<span class="dv">1</span>], npc[,<span class="dv">2</span>], <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">col=</span><span class="st">"white"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="class08_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Q16. Which of these new patients should we prioritize for follow up based on your results?</p>
</blockquote>
<p>When viewing the plot, and based off the previous conclusions drawn from the PCA plots, a malignant patient(tumor), is likely to be in the negative portion on the x axis (PC1). Thus when comparing patient 1 and 2 because patient 2 lies on the negative side amoungst the malignant patients I would predict this patient to be prioritized.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>